[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TURBOPACK = "false"
  NEXT_DISABLE_TURBOPACK = "1"
  NEXT_FONT_GOOGLE_MOCKED_RESPONSES = "true"
